name = "Stamina-Modifier-ACE"
prefix = "stamina_modifier_ace"
author = "johnb43"
template = "cba"
mainprefix = "x"
files = [
    "CHANGELOG.md",
    "meta.cpp",
    "mod.cpp",
    "LICENSE",
    "README.md"
]
folder_optionals = false
sig_version = 3
